[package]
cairo-version = "2.5.4"
name = "taleweaver"
version = "0.6.0"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate && ./scripts/default_auth.sh"
spawn = "./scripts/spawn.sh"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.6.0" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "http://localhost:5050"
# Default account for katana with seed = 0
account_address = "0xb3ff441a68610b30fd5e2abbf3a1548eb6ba6f3559f2862bf2dc757e5828ca"
private_key = "0x2bbf4f9fd0bbb2e60b0316c1fe0b76cf7a4d0198bd493ced9b8df2a3a24d68a"
world_address = "0x446f1f19ba951b59935df72974f8ba6060e5fbb411ca21d3e3e3812e3eb8df8"

[profile.taleweaver.tool.dojo.env]
rpc_url = "https://api.cartridge.gg/x/taleweaver/katana"
account_address = "0x3b58e20d18983285427c07ca6daa70eafc256c16c9546a0e805f1fc82475e59"
private_key = "0x2e7cb478df35e56d5f8cba960775db8aa77aa1fccad1607a58f752dedfab30c"
